globalVariables(
  c(
    # standard for all datasets
    "case_id",
    "provincial_case_id",
    "travel_yn",
    "locally_acquired",
    "data_details",
    "additional_info",
    "travel_history_country",
    "age",
    "sex",
    "date",
    "location",
    "location_type",
    "location_code",
    "location_code_type",
    "data_type",
    "value",
    "data_set_name",
    "package_name",
    "function_to_get_data",
    "data_details",
    "data_url",
    "license_url",
    "data_types",
    "has_geospatial_info",
    "date_report",
    "province",
    "case_source"
  )
)
